### ISSUE TITLE
Deneb Upgrade

### ISSUE THREAD

**Issue by avalonche** [flashbots/mev-boost#554]
# Task Tracking

Issue tracking for the Deneb Fork Upgrade for mev-boost.

* [x] Upgrade type and logic paths for `getHeader` and `getPayload` https://github.com/flashbots/mev-boost/pull/553
* [x] Verify proofs, commitments, blob_root of blinded payload matches the proofs, commitments and blob of the unblinded payload
* [x] Consistency across conflicting package names (see [here](https://github.com/flashbots/mev-boost-relay/pull/488#discussion_r1277903391)) https://github.com/flashbots/mev-boost/pull/560

## Dependencies

mev-boost depends on the following changes and they are all still in branch form. `go.mod` will need to be updated after the PRs are merged to upstream and point to the latest dependency.

### go-builder-client
- Fixing the ssz encoding for blob bundles https://github.com/attestantio/go-builder-client/pull/18
- Adding the builder bid structs to attestant https://github.com/attestantio/go-builder-client/pull/17
- Adding Deneb to the versioned struct for the signed header bid https://github.com/attestantio/go-builder-client/pull/19

### go-boost-utils
- Util functions to calculate the block hash and conversions https://github.com/flashbots/go-boost-utils/pull/87 
   - Will need to replace https://github.com/MariusVanDerWijden/go-ethereum/tree/4844-devnet-6 with latest geth release after the changes are merged

# Known bugs and issues

- https://github.com/flashbots/mev-boost/issues/579

**Comment by avalonche** [comment]
merged
