### ISSUE TITLE
v1 implementation tasks

### ISSUE THREAD

**Issue by metachris** [flashbots/mev-boost#95]
Tasks:
* [x] #136 
* [ ] forwarding error codes from the relay (clarify error handling if 1/n or n/n relays fail, even with different results?)

wip:
* [x] use correct error payload format - #166 
* [ ] Store registerValidator payloads and resend to relays at regular intervals https://github.com/flashbots/mev-boost/pull/149

done:
* [x] verify signatures/payloads: #138 
* [x] require relay pubkey: #143 
* [x] check relays on startup: #140
